apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubotest
spec:
  selector:
    matchLabels: 
      app: kubotest
  replicas: 1
  template:
    metadata:
      labels:
        app: kubotest
    spec:
      containers:
      - name: kubotest
        image: chrisumbel/kubotest
        ports:
        - containerPort: 80
          hostPort: 80
